[unstable]
# Prevent bindgen tool to fail on Alpine (with '[host]' section)
# see https://ledger.slack.com/archives/C04SY25SREX/p1698055418107969
host-config = true
target-applies-to-host = true

[host]
rustflags = ["-Ctarget-feature=-crt-static"]

